### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by dwrolvink** [klalle/ObsidianToHtmlConverter#2]
Hi klalle,

Just to let you know I've made something similar: https://github.com/obsidian-html/obsidian-html

Currently it seems that my version has a lot more features (that I personally require for converting my obsidian files to html), but I really like how simple your script is, and that it has no external dependencies. 

You can see all the features it implements to fully translate obsidian to markdown (and from there to html using python-markdown) here: https://obsidian-html.github.io/. 
Maybe it can be inspiration showing you what you're still missing in your script. 

I know this is a shameful plug, and I by no means mean to one-up you. (Writing a solution to a problem yourself is the best thing about programming after all). I thought it might be useful for you and the users of your script, if they need a more powerful option (with unavoidable extra setup complexity ;) )

You can remove this if this kind of posting is not okay.

**Comment by klalle** [comment]
Sweet! I just hacked together my script since I lacked this feature. I'm totally new to python as well, so I bet there are tons of improvements you could make to it - or just use your implementation =)

**Comment by dwrolvink** [comment]
Cheers! :)
